spring:
  datasource:
    initialize: true
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  thymeleaf:
    cache: false
